# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('spec', models.TextField(blank=True, null=True)),
                ('model', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
