# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='fanoutFixedValue',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='initialRunSize',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='maxRunsPerLevel',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='mergeFactor',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='skiplinksProbability',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='capacity_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='hasFunctionsNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='numberOfBits',
            field=models.IntegerField(null=True),
        ),
    ]
