# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171023_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='HashFunctionsNum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='NumOfBits',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='capacityValue',
            field=models.IntegerField(null=True),
        ),
    ]
