# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20171023_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='location',
        ),
    ]
