# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_element_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastructure',
            name='picture',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
