# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20171108_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='HashFunctionsNum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='NumOfBits',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='Utilization',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='UtilizationFunction',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='accessPartitions',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='bloomFilters',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='capacity',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='capacityFunction',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='capacityValue',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='directAddressing',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='fanout',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='fanoutFixedValue',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='fanoutFunction',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='filtersLayout',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='filtersPerLevel',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='filtersPerRun',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='head',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='initialRunSize',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='keyRetention',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='keyRetentionCompression',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='keyRetentionFunction',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='keyValueLayout',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='linksLayout',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='maxRunsPerLevel',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='mergeFactor',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='next',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='nextLinks',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='partitioning',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='partitioningFunction',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='prev',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='prevLinks',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='skiplinks',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='skiplinksProbability',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='sorted',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='tail',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='valueRetention',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='valueRetentionCompression',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='valueRetentionFunction',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='zoneMapMax',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='zoneMapMin',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
